spring.application.name=MayaFisioLumiere
server.port=8081


spring.datasource.url=jdbc:postgresql://dpg-d6jk7rhaae7s7397akb0-a.oregon-postgres.render.com/mayafisiolumiere
spring.datasource.username=mayafisiolumiere_user
spring.datasource.password=PqF3DOywvyOftLUrbWBFodPVORpRv8We
spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-test-query=SELECT 1
